# Generated by Django 5.0 on 2023-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
